import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { verifySession } from '@/lib/sessions'
import Navbar from '@/components/shared/Navbar'
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const userId = await verifySession()
  const isLoggedIn = !!userId

  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-white font-sans text-black">
        <Navbar isLoggedIn={isLoggedIn} />

        <main className="flex-1 flex">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
